version: "3.9"

services:
  car_java:
    container_name: car_java_app
    build: .
    ports:
      - "9001:9001"
    links:
      - car_postgre
    environment:
      - port=9001
      - urldb=jdbc:postgresql://car_postgre:9002/cartrack
      - userdb=postgres
      - pwdb=m3ta
    depends_on:
      - car_postgre
  car_postgre:
    container_name: car_postgre
    image: postgres:15.5
    ports:
      - "9002:5432"
    environment:
      - POSTGRES_PASSWORD=m3ta
      - POSTGRES_DB=cartrack