insert into cars (brand_id, model, year) values (1, 'Corrolla', 2013);
insert into cars (brand_id, model, year) values (1, 'Raize', 2023);
insert into cars (brand_id, model, year) values (2, 'Attitude', 2008);
insert into cars (brand_id, model, year) values (2, 'Challenger', 2023);
insert into cars (brand_id, model, year) values (3, 'Tsuru', 2006);
insert into cars (brand_id, model, year) values (3, 'Skyline', 2007);
insert into cars (brand_id, model, year) values (4, 'S80', 2007);
insert into cars (brand_id, model, year) values (4, 'S90', 2017);
insert into cars (brand_id, model, year) values (5, 'Roma', 2020);
insert into cars (brand_id, model, year) values (5, 'Purosangue', 2023);
insert into cars (brand_id, model, year) values (6, 'CX-5', 2020);
insert into cars (brand_id, model, year) values (6, 'Mazda3', 2023);
insert into cars (brand_id, model, year) values (7, 'Lobo', 2023);
insert into cars (brand_id, model, year) values (7, 'Raptor', 2023);
insert into cars (brand_id, model, year) values (8, 'Camaro', 2008);
insert into cars (brand_id, model, year) values (8, 'Onix', 2023);
insert into cars (brand_id, model, year) values (9, 'Clase E', 2023);
insert into cars (brand_id, model, year) values (9, 'Clase S', 2021);
insert into cars (brand_id, model, year) values (10, 'Jetta', 2008);
insert into cars (brand_id, model, year) values (10, 'Virtus', 2023);